### ISSUE TITLE
[chore] 프로젝트 초기 설정

### ISSUE THREAD

**Issue by RyuKwanKon** [Domitory-CheckMate/BackEnd#1]
## 📢  Feature Issue
프로젝트 초기 설정입니다.

## 📝  To-do
- [x] 기본 package 구성
- [x] 기본 entity 정의
- [x] DB 연동
- [x] base response dto 정의
- [x] error response dto 정의
- [x] base exception 정의
- [x] spring sequrity 정의
- [x] quarydsl 의존성 추가
- [x] jpa 의존성 추가
- [x] enum converter 추상화
