### ISSUE TITLE
[feat] 로그인/회원가입 기능

### ISSUE THREAD

**Issue by ziiyouth** [Domitory-CheckMate/BackEnd#10]
## 📢  Feature Issue
로그인 및 회원가입 기능을 개발합니다.

## 📝  To-do

- [x] RoomTypeConverter를 member->post로 옮기겠습니다.
- [x] 비밀번호 암호화 처리
- [x] major는 major DB에서 검색해서 정보 조회한 뒤 프론트에서 string으로 보내주는 방식 맞을까요? (일단 string 입력으로 구현하겠습니다)
- [x] 회원가입 API
- [x] 로그인 API
- [x] 이메일 중복확인 처리 - 인증번호 전송할 때
- [x] 비밀번호 재설정 API
