### ISSUE TITLE
[feat] 채팅기능

### ISSUE THREAD

**Issue by OJOJIN** [Domitory-CheckMate/BackEnd#5]
## 📢  Feature Issue
초기 단계 채팅 기능을 만듭니다. 사용자에 따른 인증이나 채팅 메세지 저장은 추후에 추가할 예정입니다.
-> 에서 거의 완성본을 만들어 버렸습니다.. 죄송합니다

## 📝  To-do
- [x] websocket config 추가
- [x] 채팅 컨트롤러 및 서비스 추가
- [x] Socket error handler 추가
- [x] Socket BaseResponse 추가
- [x] 유저 채팅방 접속 확인을 redis 로 관리
- [x] 채팅 보내기
- [x] 채팅방 불러오기
- [x] 이전 채팅 불러오기
- [x] 채팅방 입장
